### ISSUE TITLE
Create ext4 filesystem on drive without relying on name

### ISSUE THREAD

**Issue by chatton** [chatton/ansible-homelab#14]
```yaml
-  name: Create a ext4 filesystem on /dev/sdb1
   filesystem:
     fstype: ext4
    dev: /dev/sdb1
    state: present
```

We should be able to use this module to create a filesystem. However this depends on device name which can change as drives are added. Can we do this without needing to rely on name?
